from dataclasses import dataclass

@dataclass
class SuburbDefinition:
    suburb: str
    state: str
    postcode: str

SuburbDefinitions = [
    SuburbDefinition("ADAMINABY", "NSW", "2629"),
    SuburbDefinition("ADELONG", "NSW", "2729"),
    SuburbDefinition("ADJUNGBILLY", "NSW", "2727"),
    SuburbDefinition("ANGLERS REACH", "NSW", "2629"),
    SuburbDefinition("ARGALONG", "NSW", "2720"),
    SuburbDefinition("BANGADANG", "NSW", "2729"),
    SuburbDefinition("BATLOW", "NSW", "2730"),
    SuburbDefinition("BIMBERI", "NSW", "2611"),
    SuburbDefinition("BLACK CREEK", "NSW", "2729"),
    SuburbDefinition("BLOWERING", "NSW", "2720"),
    SuburbDefinition("BLUE COW", "NSW", "2624"),
    SuburbDefinition("BOGONG PEAKS WILDERNESS", "NSW", "2720"),
    SuburbDefinition("BOMBOWLEE", "NSW", "2720"),
    SuburbDefinition("BOMBOWLEE CREEK", "NSW", "2720"),
    SuburbDefinition("BRAEMAR BAY", "NSW", "2628"),
    SuburbDefinition("BRINDABELLA", "NSW", "2611"),
    SuburbDefinition("BRINGENBRONG", "NSW", "3707"),
    SuburbDefinition("BROKEN DAM", "NSW", "2629"),
    SuburbDefinition("BRUNGLE", "NSW", "2722"),
    SuburbDefinition("BRUNGLE CREEK", "NSW", "2722"),
    SuburbDefinition("BUDDONG", "NSW", "2720"),
    SuburbDefinition("BURRA", "NSW", "2653"),
    SuburbDefinition("BURRUNGUBUGGE", "NSW", "2627"),
    SuburbDefinition("CABRAMURRA", "NSW", "2629"),
    SuburbDefinition("CALIFAT", "NSW", "2729"),
    SuburbDefinition("CARABOST", "NSW", "2650"),
    SuburbDefinition("CHARLOTTE PASS", "NSW", "2624"),
    SuburbDefinition("COOLEMAN", "NSW", "2611"),
    SuburbDefinition("COOLEYS CREEK", "NSW", "2729"),
    SuburbDefinition("COPPABELLA", "NSW", "2644"),
    SuburbDefinition("COURABYRA", "NSW", "2653"),
    SuburbDefinition("COURAGAGO", "NSW", "2720"),
    SuburbDefinition("DARBALARA", "NSW", "2722"),
    SuburbDefinition("DARLOW", "NSW", "2729"),
    SuburbDefinition("ELLERSLIE", "NSW", "2729"),
    SuburbDefinition("EUCUMBENE", "NSW", "2628"),
    SuburbDefinition("GADARA", "NSW", "2720"),
    SuburbDefinition("GEEHI", "NSW", "2642"),
    SuburbDefinition("GILMORE", "NSW", "2720"),
    SuburbDefinition("GLENROY", "NSW", "2653"),
    SuburbDefinition("GOBARRALONG", "NSW", "2727"),
    SuburbDefinition("GOCUP", "NSW", "2720"),
    SuburbDefinition("GOOANDRA", "NSW", "2629"),
    SuburbDefinition("GOOBARRAGANDRA", "NSW", "2720"),
    SuburbDefinition("GRAHAMSTOWN", "NSW", "2729"),
    SuburbDefinition("GREEN HILLS", "NSW", "2730"),
    SuburbDefinition("GREG GREG", "NSW", "2642"),
    SuburbDefinition("GROSSES PLAIN", "NSW", "2627"),
    SuburbDefinition("GUNDAGAI", "NSW", "2722"),
    SuburbDefinition("GUTHEGA", "NSW", "2624"),
    SuburbDefinition("HUMULA", "NSW", "2652"),
    SuburbDefinition("INDI", "NSW", "2642"),
    SuburbDefinition("INGEBIRAH", "NSW", "2627"),
    SuburbDefinition("INGEEGOODBEE", "NSW", "2627"),
    SuburbDefinition("JACOBS RIVER", "NSW", "2627"),
    SuburbDefinition("JAGUMBA", "NSW", "2642"),
    SuburbDefinition("JAGUNGAL WILDERNESS", "NSW", "2642"),
    SuburbDefinition("JINGELLIC", "NSW", "2642"),
    SuburbDefinition("JONES BRIDGE", "NSW", "2720"),
    SuburbDefinition("KHANCOBAN", "NSW", "2642"),
    SuburbDefinition("KIANDRA", "NSW", "2629"),
    SuburbDefinition("KILLIMICAT", "NSW", "2720"),
    SuburbDefinition("KOSCIUSZKO", "NSW", "2627"),
    SuburbDefinition("KUNAMA", "NSW", "2730"),
    SuburbDefinition("LACMALAC", "NSW", "2720"),
    SuburbDefinition("LANKEYS CREEK", "NSW", "2644"),
    SuburbDefinition("LAUREL HILL", "NSW", "2649"),
    SuburbDefinition("LITTLE RIVER", "NSW", "2720"),
    SuburbDefinition("LONG PLAIN", "NSW", "2629"),
    SuburbDefinition("LOWER BAGO", "NSW", "2730"),
    SuburbDefinition("MANNUS", "NSW", "2653"),
    SuburbDefinition("MARAGLE", "NSW", "2653"),
    SuburbDefinition("MINJARY", "NSW", "2720"),
    SuburbDefinition("MOUNT ADRAH", "NSW", "2729"),
    SuburbDefinition("MOUNT HOREB", "NSW", "2729"),
    SuburbDefinition("MUNDARLO", "NSW", "2729"),
    SuburbDefinition("MUNDEROO", "NSW", "2653"),
    SuburbDefinition("MUNDONGO", "NSW", "2720"),
    SuburbDefinition("MUNYANG", "NSW", "2624"),
    SuburbDefinition("MURRAY GORGE", "NSW", "2642"),
    SuburbDefinition("NGARIGO", "NSW", "2627"),
    SuburbDefinition("NIMMO", "NSW", "2628"),
    SuburbDefinition("NUNGAR", "NSW", "2629"),
    SuburbDefinition("NURENMERENMONG", "NSW", "2649"),
    SuburbDefinition("OBERNE CREEK", "NSW", "2650"),
    SuburbDefinition("OLD ADAMINABY", "NSW", "2629"),
    SuburbDefinition("OURNIE", "NSW", "2640"),
    SuburbDefinition("PADDYS RIVER", "NSW", "2653"),
    SuburbDefinition("PERISHER VALLEY", "NSW", "2624"),
    SuburbDefinition("PILOT WILDERNESS", "NSW", "2627"),
    SuburbDefinition("PINBEYAN", "NSW", "2720"),
    SuburbDefinition("PROVIDENCE PORTAL", "NSW", "2629"),
    SuburbDefinition("RED HILL", "NSW", "2720"),
    SuburbDefinition("ROSEWOOD", "NSW", "2652"),
    SuburbDefinition("SANDY GULLY", "NSW", "2729"),
    SuburbDefinition("SHARPS CREEK", "NSW", "2729"),
    SuburbDefinition("SMIGGIN HOLES", "NSW", "2624"),
    SuburbDefinition("SNOWY PLAIN", "NSW", "2628"),
    SuburbDefinition("SOUTH GUNDAGAI", "NSW", "2722"),
    SuburbDefinition("TALBINGO", "NSW", "2720"),
    SuburbDefinition("TALMALMO", "NSW", "2640"),
    SuburbDefinition("TANTANGARA", "NSW", "2629"),
    SuburbDefinition("TARADALE", "NSW", "2653"),
    SuburbDefinition("TARCUTTA", "NSW", "2652"),
    SuburbDefinition("THREDBO", "NSW", "2625"),
    SuburbDefinition("TOLBAR", "NSW", "2629"),
    SuburbDefinition("TOOMA", "NSW", "2642"),
    SuburbDefinition("TUMBARUMBA", "NSW", "2653"),
    SuburbDefinition("TUMBLONG", "NSW", "2729"),
    SuburbDefinition("TUMORRAMA", "NSW", "2720"),
    SuburbDefinition("TUMUT", "NSW", "2720"),
    SuburbDefinition("TUMUT PLAINS", "NSW", "2720"),
    SuburbDefinition("URIARRA", "NSW", "2611"),
    SuburbDefinition("WEE JASPER", "NSW", "2582"),
    SuburbDefinition("WELAREGANG", "NSW", "2642"),
    SuburbDefinition("WEREBOLDERA", "NSW", "2720"),
    SuburbDefinition("WERMATONG", "NSW", "2720"),
    SuburbDefinition("WESTDALE", "NSW", "2653"),
    SuburbDefinition("WESTWOOD", "NSW", "2729"),
    SuburbDefinition("WILLIGOBUNG", "NSW", "2653"),
    SuburbDefinition("WILSONS VALLEY", "NSW", "2624"),
    SuburbDefinition("WINDOWIE", "NSW", "2720"),
    SuburbDefinition("WONDALGA", "NSW", "2729"),
    SuburbDefinition("WYANGLE", "NSW", "2720"),
    SuburbDefinition("YAOUK", "NSW", "2629"),
    SuburbDefinition("YARRANGOBILLY", "NSW", "2720"),
    SuburbDefinition("YAVEN CREEK", "NSW", "2729"),
]